# stdlib
from typing import List, Literal

# third-party
from fastapi import APIRouter, Depends, Path, Body, Query, status
from pydantic import constr

# internal/local
from app.services.auth_service import get_user_from_token
from app.models.auth_model import MavanUser
from app.services.chat_service import rename_chat, delete_chat_and_messages, find_paginated_chats_for_user, \
    find_chat_by_id, search_chat_message
from app.models.chat_model import ChatUpdate, ChatBaseResponse, ChatResponse

router = APIRouter()


@router.get("/api/v1/chats", summary="Get paginated list of user chats sorted by updated_at DESC",
            response_model=List[ChatBaseResponse],
            status_code=status.HTTP_200_OK,
            response_model_exclude_none=True,
            responses={400: {"description": "Bad request"},
                       404: {"description": "Project not found"},
                       500: {"description": "Internal Server Error"}})
async def api_find_paginated_chats(
        limit: int = Query(20, ge=1, le=100),
        before: str | None = Query(None,
                                   description="RFC3339 timestamp (ISO 8601) to paginate before, e.g. 2025-07-02T14:59:49.508Z"),
        project_id: str | None = Query(None, description="Filter by project id"),
        current_user: MavanUser = Depends(get_user_from_token)
):
    return await find_paginated_chats_for_user(current_user.username, limit, before, project_id)


@router.get("/api/v1/chats/{chat_id}",
            summary="Find a chat by its ID and an optional parameter indicating if the title was generated by LLM",
            response_model=ChatResponse,
            status_code=status.HTTP_200_OK,
            response_model_exclude_none=True,
            responses={400: {"description": "Bad request"},
                       404: {"description": "Chat not found"},
                       500: {"description": "Internal Server Error"}})
async def api_find_chat_by_id(
        chat_id: str = Path(..., description="ID of the chat"),
        current_user: MavanUser = Depends(get_user_from_token),
):
    return await find_chat_by_id(current_user.username, chat_id)


@router.patch("/api/v1/chats/{chat_id}", summary="Rename chat title",
              response_model=ChatResponse,
              status_code=status.HTTP_200_OK,
              response_model_exclude_none=True,
              responses={400: {"description": "Bad request"},
                         404: {"description": "Chat not found"},
                         500: {"description": "Internal Server Error"}})
async def api_rename_chat_title(
        chat_id: str = Path(..., description="ID of the chat to rename"),
        update_data: ChatUpdate = Body(..., description="New title for the chat"),
        current_user: MavanUser = Depends(get_user_from_token)
):
    return await rename_chat(chat_id, update_data, current_user.username)


@router.delete("/api/v1/chats/{chat_id}", summary="Delete a chat and its messages",
               status_code=status.HTTP_204_NO_CONTENT,
               responses={400: {"description": "Bad request"},
                          404: {"description": "Chat not found"},
                          500: {"description": "Internal Server Error"}})
async def api_delete_chat_and_messages_endpoint(
        chat_id: str = Path(..., description="ID of the chat to delete"),
        current_user: MavanUser = Depends(get_user_from_token)
):
    await delete_chat_and_messages(chat_id, current_user.username)


@router.post("/api/v1/chats/search", summary="Search for matching text in user/assistant messages and chat titles",
             status_code=status.HTTP_200_OK,
             responses={400: {"description": "Bad request"},
                        500: {"description": "Internal Server Error"}})
async def api_search_chat_message_endpoint(
        text: constr(strip_whitespace=True, min_length=1) = Body(..., embed=True),
        search_in: List[Literal["title", "content_user", "content_assistant"]] = Query(
            default=["title", "content_user", "content_assistant"]),
        skip: int = Query(default=0, ge=0),
        limit: int = Query(default=20, ge=1, le=100),
        current_user: MavanUser = Depends(get_user_from_token)
) -> List[dict]:
    return await search_chat_message(text, search_in, skip, limit, current_user.username)
